name: Call some Dagger functions

on:
  workflow_dispatch:

jobs:

  build:

    name: Call a Dagger Function
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7


      - name: Cloc - Call cloc-dir Dagger function
        uses: dagger/dagger-for-github@6210aa04aaf743e52a7315449e213bb85cd828ce # v5.10.0
        with:
          version: "latest"
          module: github.com/staticaland/daggerverse/cloc@main
          verb: call
          args: cloc-dir --directory-arg='.' --yaml-output


      - name: Renovate - Call run Dagger function
        uses: dagger/dagger-for-github@6210aa04aaf743e52a7315449e213bb85cd828ce # v5.10.0
        with:
          version: "latest"
          module: github.com/staticaland/daggerverse/renovate@main
          verb: call
          args: run
